Projekat/Models/Show.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using static Projekat.Models.Enums;

namespace Projekat.Models
{
    [Serializable]
    public class Show
    {
        public string Name { get; set; }

        public Enums.ShowType Type { get; set; }

        public int NumberOfSeats { get; set; }

        public DateTime Start { get; set; }

        public TimeSpan Duration { get; set; }

        public float Price { get; set; }

        public ShowStatus Status { get; set; }

        public Address Address { get; set; }

        public float Rating { get; set; }

        public List<Comment> Comments { get; set; }

        public string Picture { get; set; }

        public Show()
        {

        }

        public Show(string name, ShowType type, int number, DateTime start, float price, ShowStatus status, Address address, string picture)
        {
            Name = name;
            Type = type;
            NumberOfSeats = number;
            Start = start;
            Price = price;
            Status = status;
            Address = address;
            Comments = new List<Comment>();
            Picture = picture;
        }

        public float CalculateRating()
        {
            Database.ReadData();
            int i = 0;
            int value = 0;
            
            foreach (Comment c in Database.comments)
            {
                if (c.Show == this.Name)
                {
                    value += c.Rating;
                    i++;
                }
            }
            if(i != 0)
            {
                value = value / i;
                return value;
            }
            return value;
        }
    }
}

Projekat/Controllers/SellerController.cs
using Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Projekat.Controllers
{
    public class SellerController : Controller
    {
        // GET: Seller
        public ActionResult Index()
        {
            return View("~/Views/Seller/LoggedInSeller.cshtml");
        }
        public ActionResult MyProfile()
        {
            ViewBag.korisnik = Session["user"];
            return View("~/Views/Seller/MyProfile.cshtml");
        }
        [HttpPost]
        public ActionResult PromeniPodatke(string name, string surname, string password)
        {
            Database.ReadData();

            User user = (User)Session["user"];
            string username = user.Username;

            if (!name.Equals(""))
            {
                user.Name = name;
            }
            if (!surname.Equals(""))
            {
                user.Surname = surname;
            }
            if (!password.Equals(""))
            {
                user.Password = password;
            }

            foreach (User u in Database.users)
            {
                if (u.Username == user.Username)
                {
                    Database.users.Remove(u);
                    Database.users.Add(user);
                    Database.UpdateData();
                }
            }

            ViewBag.user = user;

            return View("~/Views/Seller/MyProfile.cshtml");
        }

        public ActionResult AddShow()
        {
            return View("~/Views/Seller/AddShow.cshtml");
        }
        public ActionResult NovaShow()
        {
            Database.ReadData();

            Enums.ShowType type = new Enums.ShowType();
            

            string filename = "";

            


            if (Request["type"].Equals(Enums.ShowType.Festival))
            {
                type = Enums.ShowType.Festival;
            }
            if (Request["type"].Equals(Enums.ShowType.Concert))
            {
                type = Enums.ShowType.Concert;
            }
            if (Request["type"].Equals(Enums.ShowType.Cinema))
            {
                type = Enums.ShowType.Cinema;
            }
            if (Request["type"].Equals(Enums.ShowType.Theatre))
            {
                type = Enums.ShowType.Theatre;
            }

            Address ad = new Address(Request["city"], Request["street"], Int32.Parse(Request["zipCode"]));
            

            foreach (Show s in Database.shows)
            {
                if ((s.Address.Street.Equals(Request["street"])) && (s.Start.Equals(Request["date"])) && (s.Duration.Equals(Request["duration"])))
                {
                    return View("~/Views/Seller/ShowExist.cshtml");
                }
            }
            Show show = new Show(Request["naziv"], type, Int32.Parse(Request["brojMesta"]), DateTime.Parse(Request["date"]), float.Parse(Request["price"]), Enums.ShowStatus.Inactive, ad, filename);
            Database.showshold.Add(show);

            
            return View("~/Views/Seller/LoggedInSeller.cshtml");
        }

        public ActionResult EditShow()
        {
            List<Show> shows = Database.shows;
            ViewBag.shows = shows;
            return View("~/Views/Seller/Manifestacije.cshtml");
        }
        public ActionResult EditShowData()
        {
            List<Show> shows = Database.shows;
            foreach (Show s in shows)
            {
                if (s.Name.Equals(Request["ID"]))
                {
                    ViewBag.show = s;
                }
            }
            return View("~/Views/Seller/EditShow.cshtml");
        }

        [HttpPost]
        public ActionResult Edit(string name, string number, string date, string duration, string city, string street, string zipcode, string price)
        {
            Database.ReadData();

            Show show = new Show();
           

            foreach (Show s in Database.shows)
            {
                if (s.Name.Equals(name))
                {
                    show = s;
                    Database.shows.Remove(s);
                }
            }


            if (!name.Equals(""))
            {
                show.Name = name;
            }
            if (!number.Equals(""))
            {
                show.NumberOfSeats = Int32.Parse(number);
            }
            if (!date.Equals(""))
            {
                show.Start = DateTime.Parse(date);
            }
            if (!duration.Equals(""))
            {
                show.Duration = TimeSpan.Parse(duration);
            }
            if (!city.Equals(""))
            {
                show.Address.City = city;
            }
            if (!street.Equals(""))
            {
                show.Address.Street = street;
            }       
            if (!zipcode.Equals(""))
            {
                show.Address.ZipCode = Int32.Parse(zipcode);
            }
            if (!price.Equals(""))
            {
                show.Price = Int32.Parse(price);
            }

            Database.shows.Add(show);
            Database.UpdateData();
            


            ViewBag.show = show;

            return View("~/Views/Seller/EditShow.cshtml");
        }
        public ActionResult ShowTicketsView()
        {
            Database.ReadData();
            ViewBag.tickets = Database.tickets;
            return View("~/Views/Seller/ShowTickets.cshtml");
        }

        public ActionResult SearchTickets()
        {
            Database.ReadData();
            List<Ticket> searchedTickets = new List<Ticket>();

            foreach (Ticket t in Database.tickets)
            {
                DateTime date = t.Time;
                DateTime dateFrom = DateTime.Parse(Request["dateFrom"]);
                DateTime dateTo = DateTime.Parse(Request["dateTo"]);

                int compareFrom = DateTime.Compare(date, dateFrom);
                int compareTo = DateTime.Compare(date, dateTo);


                int priceFrom = Int32.Parse(Request["priceFrom"]);
                int priceTo = Int32.Parse(Request["priceTo"]);

                if ((compareFrom >= 0) && (compareTo <= 0) && (t.TotalPrice >= priceFrom) && (t.TotalPrice <= priceTo))
                {
                    if (t.Show.Name.ToUpper().Equals(Request["search_value"].ToUpper()))
                    {

                        if (!searchedTickets.Contains(t))
                        {
                            searchedTickets.Add(t);
                        }
                    }

                }

            }
            ViewBag.tickets = searchedTickets;
            return View("~/Views/Buyer/ShowBoughtTickets.cshtml");
        }
        public ActionResult SortTickets()
        {
            Database.ReadData();
            List<Ticket> allTickets = Database.tickets;
            List<Ticket> sortedTickets = new List<Ticket>();

            if (Request["sortBy"].Equals("name"))
            {
                if (Request["sortType"].Equals("ascending"))
                {
                    sortedTickets = allTickets.OrderBy(o => o.Show.Name).ToList();
                }
                else if (Request["sortType"].Equals("descending"))
                {
                    sortedTickets = allTickets.OrderByDescending(o => o.Show.Name).ToList();
                }
            }
            else if (Request["sortBy"].Equals("dateITime"))
            {
                if (Request["sortType"].Equals("ascending"))
                {
                    sortedTickets = allTickets.OrderBy(o => o.Time).ToList();

                }
                else if (Request["sortType"].Equals("descending"))
                {
                    sortedTickets = allTickets.OrderByDescending(o => o.Time).ToList();

                }
            }
            else if (Request["sortBy"].Equals("price"))
            {
                if (Request["sortType"].Equals("ascending"))
                {
                    sortedTickets = allTickets.OrderBy(o => o.TotalPrice).ToList();
                }
                else if (Request["sortType"].Equals("descending"))
                {
                    sortedTickets = allTickets.OrderByDescending(o => o.TotalPrice).ToList();
                }
            }
            ViewBag.tickets = sortedTickets;
            return View("~/Views/Buyer/ShowBoughtTickets.cshtml");
        }

        public ActionResult FilterTickets()
        {

            Database.ReadData();
            List<Ticket> filteredTickets = new List<Ticket>();

            if ((!Request["type"].Equals("")) && (!Request["status"].Equals("")))
            {
                if (Request["status"].Equals("active"))
                {
                    if (Request["type"].Equals("Regular"))
                    {
                        foreach (Ticket t in Database.tickets)
                        {
                            if ((t.Status == Enums.TicketStatus.Reserved) && (t.TicketType == Enums.TicketType.Regular))
                            {
                                filteredTickets.Add(t);
                            }
                        }
                    }
                    else if (Request["type"].Equals("FanPit"))
                    {
                        foreach (Ticket t in Database.tickets)
                        {
                            if ((t.Status == Enums.TicketStatus.Reserved) && (t.TicketType == Enums.TicketType.FanPit))
                            {
                                filteredTickets.Add(t);
                            }
                        }

                    }
                    else if (Request["type"].Equals("VIP"))
                    {
                        foreach (Ticket t in Database.tickets)
                        {

Projekat/Views/Seller/AddShow.cshtml
@{
    ViewBag.Title = "AddShow";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css">
    <script type="text/javascript">
        function onRequired() {
            var fieldForm = document.getElementsByName("name")[0].value;
            var fieldForm1 = document.getElementsByName("numberSpots")[0].value;
            var fieldForm2 = document.getElementsByName("date")[0].value;
            var fieldForm3 = document.getElementsByName("time")[0].value;
            var fieldForm4 = document.getElementsByName("city")[0].value;
            var fieldForm5 = document.getElementsByName("street")[0].value;
            var fieldForm6 = document.getElementsByName("zipCode")[0].value;
            if (fieldForm == "" || fieldForm1 == "" || fieldForm2 == "" || fieldForm3 == "" || fieldForm4 == "" || fieldForm5 == "" || fieldForm6 == "") {
                document.getElementById("message").innerHTML = "All fields must be filled";
                return false;
            }

            return true;
        }
    </script>
</head>
<body>
    <h3>Add new Show</h3>
    <br />
    <form method="post" action="~/Seller/NewShow" enctype="multipart/form-data" onsubmit="return onRequired()">
        <input type="text" placeholder="Show name" name="name" required /><br /><br />
        <select name="type" required>
            <option value="" selected disabled>Choose a type</option>
            <option value="concert">Concert</option>
            <option value="Festival">Festival</option>
            <option value="Theatre">Theatre</option>
            <option value="Cinema">Cinema</option>
        </select> <br /><br />
        <input type="text" placeholder="Number of seats" name="numberSpots" required /><br /><br />
        <input type="date" min="2020-07-04" max="2025-12-31" name="date" value="2021-07-04" required /><br /><br />
        <input type="time" name="time" value="21:00" required /><br /><br />
        <input type="text" name="price" placeholder="Price" required /><br /><br />
        <input type="text" name="city" placeholder="City" required /><br /><br />
        <input type="text" name="street" placeholder="Street" required /><br /><br />
        <input type="text" name="zipCode" placeholder="ZipCode" required /><br /><br />
        <input name="slika" type="file" placeholder="Add picture" required /><br /><br />

        <input type="submit" value="Add Show" /><br />
    </form>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>

</body>

Projekat/Views/Seller/AllComments.cshtml
@{
    ViewBag.Title = "AllComments";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <h2>Comments on hold</h2>
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th>Type</th>
            <th>Show name</th>
            <th>Buyer</th>
            <th>Comment</th>
            <th>Rating</th>
        </tr>
        @foreach (var c in ViewBag.comments)
        {
            <tr>
                <td>Approved</td>
                <td>
                    @c.Show <br />
                </td>

                <td>@c.Buyer</td>
                <td>@c.Post</td>
                <td>
                    @c.Rating

                </td>
            </tr>
        }
        @foreach (var c in ViewBag.commentsRejected)
        {
            <tr>
                <td>Rejected</td>
                <td>
                    @c.Show <br />
                </td>

                <td>@c.Buyer</td>
                <td>@c.Post</td>
                <td>
                    @c.Rating &nbsp;

                </td>
            </tr>
        }
    </table>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
</body>

Projekat/Views/Seller/ApproveComment.cshtml
@{
    ViewBag.Title = "ApproveComment";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <h2>Comments on hold</h2>
    <table cellpadding="0" cellspacing="0">
            <tr>Show name</th>
            <th>Buyer</th>
            <th>Comment</th>
            <th>Rating</th>
            <th></th>
        </tr>
        @foreach (var c in ViewBag.comments)
        {
            <tr>
                <td>
                    @c.Show <br />
                </td>

                <td>@c.Buyer</td>
                <td>@c.Post</td>
                <td>
                    @c.Rating

                </td>
                <td>
                    <form action="~/Seller/Approve" method="post">
                        <input type="hidden" name="IDComment" value="@c.Post" /><br />
                        <input type="hidden" name="IDBuyer" value="@c.Buyer" /><br />
                        <input type="hidden" name="IDShow" value="@c.Show" /><br />
                        <input type="submit" value="Approve" />
                    </form>
                    <form action="~/Seller/Reject" method="post">
                        <input type="hidden" name="IDComment" value="@c.Post" /><br />
                        <input type="hidden" name="IDBuyer" value="@c.Buyer" /><br />
                        <input type="hidden" name="IDShow" value="@c.Show" /><br />
                        <input type="submit" value="Reject" />
                    </form>
                </td>


            </tr>

        }
    </table>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>

</body>

Projekat/Views/Seller/EditShow.cshtml
@{
    ViewBag.Title = "EditShow";
}

<head>
    <link rel="stylesheet" href="~/Content/basic.css" type="text/css" />
</head>
<body>
    <h2>Edit Shows</h2>
    <br />
    <br />
    <br />
    <br />
    <form action="/Seller/Edit" method="post">
        <input type="text" hidden value="@ViewBag.show.Name" name="id" />
        <table border="1">
            <tr>
                <td id="first">Name:</td>
                <td><input type="text" value="@ViewBag.show.Name" name="name" /></td>
            </tr>
            <tr>
                <td id="first">Number of seats:</td>
                <td><input type="text" value="@ViewBag.show.NumberOfSeats" name="numberSeats" /></td>
            </tr>
            <tr>
                <td id="first">Date:</td>
                <td><input type="date" min="2020-07-04" max="2025-12-31" value="@ViewBag.show.Start" name="date" /></td>
            </tr>
            <tr>
                <td id="first">Duration:</td>
                <td><input type="time" value="@ViewBag.show.Duration" name="duration" /></td>
            </tr>
            <tr>
                <td id="first">City:</td>
                <td><input type="text" value="@ViewBag.show.Address.City" name="city" /></td>
            </tr> 
            <tr>
                <td id="first">Street:</td>
                <td><input type="text" value="@ViewBag.show.Address.Street" name="street" /></td>
            </tr>
            <tr>
                <td id="first">ZipCode:</td>
                <td><input type="text" value="@ViewBag.show.Address.ZipCode" name="zipcode" /></td>

            </tr>
            <tr>
                <td id="first">Price:</td>
                <td><input type="text" value="@ViewBag.show.Price" name="price" /></td>
            </tr>

        </table>
        <input type="submit" value="Edit profile" />
    </form>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</body>

Projekat/Views/Seller/LoggedInSeller.cshtml
@{
    ViewBag.Title = "LoggedInSeller";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css">
</head>
<body>

    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("My profile", "MyProfile", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Add Show", "AddShow", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Edit Show", "EditShow", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Show all bought tickets", "ShowTicketsView", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Approve comment", "ApproveCommentView", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("All comments", "ShowComments", "Seller")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Log Out", "Logout", "Seller")
    </div>
    <br />
    <br />
    <br />
    <br />

</body>

Projekat/Views/Seller/MyProfile.cshtml
@{
    ViewBag.Title = "MyProfile";
}

<head>
    <link rel="stylesheet" href="~/Content/basic.css" type="text/css" />
</head>
<body>
    <br />
    <br />
    <br />
    <br />
    <form action="/Seller/EditProfile" method="post">
        <table border="1">
            <tr>
                <td id="first">Name:</td>
                <td><input type="text" value="@ViewBag.user.Name" name="name" /></td>
            </tr>
            <tr>
                <td id="first">Surname:</td>
                <td><input type="text" value="@ViewBag.user.Surname" name="lastname" /></td>
            </tr>
            <tr>
                <td id="first">password:</td>
                <td><input type="text" value="@ViewBag.user.Password" name="password" /></td>
            </tr>
        </table>
        <input type="submit" value="Submit changes" />
    </form>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Admin");
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</body>

Projekat/Views/Seller/NoCommentsOnHold.cshtml
@{
    ViewBag.Title = "NoCommentsOnHold";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <h2>No more comments on hold.</h2>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
</body>

Projekat/Views/Seller/ShowExist.cshtml
@{
    ViewBag.Title = "ShowExist";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" />
</head>
<body>
    <h2>Unable to add show, it already exists.</h2>
    @Html.ActionLink(">>Home", "AddShow", "Seller")
    <br />
    <br />
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</body>

Projekat/Views/Seller/ShowTickets.cshtml
@{
    ViewBag.Title = "ShowTickets";
}

@{
    ViewBag.Title = "ShowTickets";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <div>
        <form method="post" action="~/Seller/ShowTickets">
            <br />
            Search:
            <input type="text" placeholder="Search ticket" name="search_value" value="" required />
            <br />
            <br />

            &nbsp;
            <select name="priceFrom" required>
                <option value="" selected disabled hidden>Minimum price</option>
                <option value="1000">1000</option>
                <option value="2000">2000</option>
                <option value="3000">3000</option>
                <option value="4000">4000</option>
                <option value="5000">5000</option>
                <option value="10000">10000</option>
                <option value="15000">15000</option>
                <option value="20000">20000</option>
            </select>
            &nbsp;
            <select name="priceTo" required>
                <option value="" selected disabled hidden>Maximum price</option>
                <option value="5000">5000</option>
                <option value="10000">10000</option>
                <option value="15000">15000</option>
                <option value="20000">20000</option>
                <option value="25000">25000</option>
                <option value="30000">30000</option>
                <option value="35000">35000</option>
                <option value="100000">100000</option>
            </select>
            &nbsp; From: &nbsp; <input type="date" name="datumFrom" min="2021-01-01" max="2025-12-31" value="" required />
            &nbsp; To: &nbsp;<input type="date" name="datumTo" min="2021-01-01" max="2025-12-31" value="" required />
            &nbsp;<input type="submit" value="Search" />
        </form>
    </div>
    <br />
    <div>
        Sort search:
        <form method="post" action="~/Seller/SortTickets">
            &nbsp; <select name="sortType">
                <option value="ascending">Ascending</option>
                <option value="descending">Descending</option>
            </select>
            &nbsp; <select name="sortBy">
                <option value="name">Name</option>
                <option value="dateITime">Date and time</option>
                <option value="price">Price</option>
            </select>
            &nbsp;<input type="submit" value="Sort" />
        </form>
    </div>
    <br />
    <div>
        Filter search:
        <form method="post" action="~/Seller/FilterTickets">
            &nbsp;  <select name="type">
                <option value="">Choose ticket type</option>
                <option value="Regular">Regular</option>
                <option value="FanPit">FanPit</option>
                <option value="VIP">VIP</option>
            </select>
            &nbsp; <select name="status">
                <option value="">Choose show status</option>
                <option value="active">Available tickets</option>
                <option value="inactive">Sold out tickets</option>
            </select>
            &nbsp; <input type="submit" value="Filter" />
        </form>
    </div>
    <table>
        <tr>
            <th>ID:</th>
            <th>Show</th>
            <th>Date</th>
            <th>Duration</th>
            <th>Total price</th>
            <th>Amount</th>
            <th>Ticket type</th>

        </tr>
        @foreach (var t in ViewBag.tickets)
        {
            <tr>
                <td>@t.Id</td>
                <td>@t.Show</td>
                <td>@t.Time</td>
                <td>@t.Duration</td>
                <td>@t.TotalPrice</td>
                <td>@t.Amount</td>
                <td>@t.TicketType</td>
            </tr>
        }
    </table>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
</body>

Projekat/Views/Seller/Shows.cshtml
@{
    ViewBag.Title = "Shows";
}


<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Date</th>
            <th>Duration</th>
            <th>Location</th>
            <th>Price</th>
            <th>Rating</th>
            <th>Poster</th>
        </tr>
        @foreach (var s in ViewBag.shows)
        {
            <tr>
                <td>
                    @s.Name <br />
                    <form action="~/Seller/EditShowData" method="post">
                        <input type="hidden" name="ID" value="@s.Name" /><br />
                        <input type="submit" value="Edit Show" />
                    </form>
                </td>

                <td>@s.Type</td>
                <td>@s.Start</td>
                <td>@s.Duration</td>
                <td>@s.Address.City, @s.Address.Street, @s.Address.ZipCode</td>
                <td>@s.Price</td>
                <td>@s.Rating</td>
                <td><img alt="show picture" src=@s.Slika /></td>
            </tr>

        }
    </table>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Seller");
    </div>
</body>