Projekat/Controllers/BuyerController.cs
using Projekat.Models;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Web.Security;

namespace Projekat.Controllers
{
    public class BuyerController : Controller
    {
        
        public ActionResult Index()
        {
            return View("~/Views/Buyer/LoggedInBuyer.cshtml");
        }
        public ActionResult MyProfile ()
        {
            ViewBag.user = Session["user"];
            return View("~/Views/Buyer/MyProfile.cshtml");
        }
        [HttpPost]
        public ActionResult EditProfile(string name, string surname, string password)
        {
            Database.ReadData();

            User user = (User)Session["user"];
            string username = user.Username;

            if (!name.Equals(""))
            {
                user.Name = name;
            }
            if (!surname.Equals(""))
            {
                user.Surname = surname;
            }
            if (!password.Equals(""))
            {
                user.Password = password;
            }

            foreach (User u in Database.users)
            {
                if (u.Username == user.Username)
                {
                    Database.users.Remove(u);
                    Database.users.Add(user);
                    Database.UpdateData();
                }
            }

            ViewBag.user = user;

            return View("~/Views/Buyer/MyProfile.cshtml");


        }

        public ActionResult BuyTicketView()
        {
            Database.ReadData();
            List<Show> allShows = Database.shows;
            ViewBag.shows = Database.shows;
            return View("~/Views/Buyer/BuyTicket.cshtml");
        }

        public ActionResult BuyFormView()
        {
            Database.ReadData();
            
            string id = Request["ID"];
            foreach (Show s in Database.shows)
            {
                if (s.Name.Equals(Request["ID"]))
                {
                    ViewBag.showBuy = s;

                }
            }
            return View("~/Views/Buyer/BuyTicketForm.cshtml");
        }

        public ActionResult Confirmation()
        {
            Database.ReadData();
            User u = (User)Session["user"];
            
            Show show = new Show();

            foreach (Show s in Database.shows)
            {
                if (s.Name.Equals(Request["ID"]))
                {
                    show = s;
                    ViewBag.showBuy = s;

                }
            }
            int number = Int32.Parse(Request["amount"]);
            double price;
            double raw_price;
            Enums.TicketType type = new Enums.TicketType();

            if (Request["type"].Equals("Regular"))
            {
                type = Enums.TicketType.Regular;

            }
            if (Request["type"].Equals("FanPit"))
            {
                type = Enums.TicketType.FanPit;

            }
            if (Request["type"].Equals("VIP"))
            {
                type = Enums.TicketType.VIP;

            }

            if (show.NumberOfSeats >= number)
            {
                if (u.Type.Discount > 0)
                {
                    ViewBag.Discount = u.Type.Discount;
                    if (type == Enums.TicketType.Regular)
                    {
                        raw_price = show.Price * number;
                        price = raw_price - (u.Type.Discount / 100 * raw_price);
                        ViewBag.price = price;
                    }
                    else if (type == Enums.TicketType.FanPit)
                    {
                        raw_price = show.Price * number * 2;
                        price = raw_price - (u.Type.Discount / 100 * raw_price);
                        ViewBag.price = price;
                    }
                    else if (type == Enums.TicketType.VIP)
                    {
                        raw_price = show.Price * number * 4;
                        price = raw_price - (u.Type.Discount / 100 * raw_price);
                        ViewBag.price = price;
                    }

                }
                else
                {
                    if (type == Enums.TicketType.Regular)
                    {
                        price = show.Price * number;
                        ViewBag.price = price;
                    }
                    else if (type == Enums.TicketType.FanPit)
                    {
                        price = show.Price * number * 2;
                        ViewBag.price = price;
                    }
                    else if (type == Enums.TicketType.VIP)
                    {
                        price = show.Price * number * 4;
                        ViewBag.price = price;
                    }


                }
            }
            else
            {
                ViewBag.showBuy = show;
                ViewBag.seatnumber = show.NumberOfSeats;
                return View("~/Views/Buyer/NoTickets.cshtml");
            }

            ViewBag.type = type;
            ViewBag.ticketnumber = number;
            return View("~/Views/Buyer/Confirmation.cshtml");
        }

        public ActionResult Buy()
        {
            Database.ReadData();

            int amount = Int32.Parse(Request["ticketNumber"]);

            
            User u = (User)Session["user"];
            


            
            Enums.TicketType type = new Enums.TicketType();

            if (Request["type"].Equals("Regular"))
            {
                type = Enums.TicketType.Regular;

            }
            if (Request["type"].Equals("FanPit"))
            {
                type = Enums.TicketType.FanPit;

            }
            if (Request["type"].Equals("VIP"))
            {

                type = Enums.TicketType.VIP;
            }

            foreach (Show s in Database.shows)
            {
                if (Request["ID"].Equals(s.Name))
                {
                    int maxId = -1;
                    foreach (var item in Database.tickets)
                    {
                        if (item.ID > maxId)
                        {
                            maxId = item.ID;
                        }
                    }
                    
                    Ticket t = new Ticket(s, s.Start, float.Parse(Request["price"]), u.Username, Enums.TicketStatus.Reserved, s.Type, amount);
                    t.ID = maxId + 1;
                    s.NumberOfSeats -= amount;

                    Database.tickets.Add(t);
                    Database.UpdateData();
                    
                    if (type == Enums.TicketType.Regular)
                    {
                        u.Points = u.Points + (Int32.Parse(s.Price.ToString()) / 1000 * 133);
                        u.Type.ReqPoints = u.Type.ReqPoints - u.Points;


                    }
                    if (type == Enums.TicketType.FanPit)
                    {
                        u.Points = u.Points + ((Int32.Parse(s.Price.ToString()) * 2) / 1000 * 133);
                        u.Type.ReqPoints = u.Type.ReqPoints - u.Points;

                    }
                    if (type == Enums.TicketType.VIP)
                    {
                        u.Points = u.Points + ((Int32.Parse(s.Price.ToString()) * 4) / 1000 * 133);
                        u.Type.ReqPoints = u.Type.ReqPoints - u.Points;

                    }

                    int points = u.Points;
                    if (u.Points >= 1000)
                    {
                        u.Type.Name = "Bronze";
                        u.Type.Discount = 1;
                        u.Type.ReqPoints = 3000;

                    }
                    else if (u.Points >= 3000)
                    {
                        u.Type.Name = "Silver";
                        u.Type.Discount = 10;
                        u.Type.ReqPoints = 5000;
                    }
                    else if (u.Points >= 5000)
                    {
                        u.Type.Name = "Gold";
                        u.Type.Discount = 20;
                        u.Type.ReqPoints = 10000;
                    }

                    Database.users.Remove(Database.users.FirstOrDefault(x => x.Username == u.Username));
                    Database.users.Add(u);
                    Database.UpdateData();
                        
                }
            }
            return View("~/Views/Buyer/SuccessfulBuy.cshtml");
        }

        public ActionResult BoughtTicketsView()
        {
            Database.ReadData();
            User u = (User)Session["user"];
           

            ViewBag.tickets = Database.tickets;

            return View("~/Views/Buyer/ShowBoughtTickets.cshtml");
        }

        public ActionResult Search()
        {
            Database.ReadData();
            User u = (User)Session["user"];
            List<Ticket> searchedTickets = new List<Ticket>();

            foreach (Ticket t in Database.tickets)
            {
                DateTime date = t.Time;
                DateTime dateFrom = DateTime.Parse(Request["dateFrom"]);
                DateTime dateTo = DateTime.Parse(Request["dateTo"]);

                int compareFrom = DateTime.Compare(date, dateFrom);
                int compareTo = DateTime.Compare(date, dateTo);


                int priceFrom = Int32.Parse(Request["priceFrom"]);
                int priceTo = Int32.Parse(Request["priceTo"]);

                if ((compareFrom >= 0) && (compareTo <= 0) && (t.TotalPrice >= priceFrom) && (t.TotalPrice <= priceTo))
                {
                    if (t.Show.Name.ToUpper().Equals(Request["search_value"].ToUpper()))
                    {

                        if (!searchedTickets.Contains(t))
                        {
                            searchedTickets.Add(t);
                        }
                    }

                }

            }

Projekat/Views/Buyer/BuyTicket.cshtml
@{
    ViewBag.Title = "BuyTicket";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <h2>Shows</h2>
    <div>
        <div>
            <form method="post" action="~/Shows/Search">
                <br />
                Search:
                <input type="text" placeholder="Search shows" name="search_value" value="" required />
                <br />
                <br />

                &nbsp;
                <select name="priceFrom" required>
                    <option value="" selected disabled hidden>Minimum price</option>
                    <option value="1000">1000</option>
                    <option value="2000">2000</option>
                    <option value="3000">3000</option>
                    <option value="4000">4000</option>
                    <option value="5000">5000</option>
                    <option value="6000">6000</option>
                    <option value="7000">7000</option>
                    <option value="8000">8000</option>
                    <option value="9000">9000</option>
                    <option value="10000">10000</option>
                </select>
                &nbsp;
                <select name="priceTo" required>
                    <option value="" selected disabled hidden>Maximum price</option>
                    <option value="1000">1000</option>
                    <option value="2000">2000</option>
                    <option value="3000">3000</option>
                    <option value="4000">4000</option>
                    <option value="5000">5000</option>
                    <option value="6000">6000</option>
                    <option value="7000">7000</option>
                    <option value="8000">8000</option>
                    <option value="9000">9000</option>
                    <option value="10000">10000</option>
                </select>
                &nbsp; From: &nbsp; <input type="date" name="dateFrom" min="2020-09-23" max="2025-12-31" value="" required />
                &nbsp; To: &nbsp;<input type="date" name="dateTo" min="2020-09-23" max="2025-12-31" value="" required />
                &nbsp;<input type="submit" value="Search" />
            </form>
        </div>
        <br />
        <div>
            Sort search:
            <form method="post" action="~/Shows/Sort">
                &nbsp; <select name="sortType">
                    <option value="ascending">Ascending</option>
                    <option value="descending">Descending</option>
                </select>
                &nbsp; <select name="SortBy">
                    <option value="name">Name</option>
                    <option value="dateITime">Date and Time</option>
                    <option value="price">Price</option>
                    <option value="location">Location</option>
                </select>
                &nbsp;<input type="submit" value="Sort" />
            </form>
        </div>
        <br />

        <div>
            Filter search:
            <form method="post" action="~/Shows/Filter">
                &nbsp;  <select name="type">
                    <option value="">Choose show type</option>
                    <option value="concert">Concerts</option>
                    <option value="festivals">Festivals</option>
                    <option value="theater">Theater</option>
                    <option value="cinema">Cinema</option>
                </select>
                &nbsp; <select name="availability">
                    <option value="">Choose availability</option>
                    <option value="available">Available tickets</option>
                    <option value="unavailable">Unavailable tickets</option>
                </select>
                &nbsp; <input type="submit" value="Filter" />
            </form>
        </div>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Date</th>
                <th>Duration</th>
                <th>Location</th>
                <th>Price</th>
                <th>Rating</th>
                <th>Poster</th>
                <th></th>
            </tr>
            @foreach (var s in ViewBag.shows)
            {
                <tr>
                    <td>
                        @s.Name <br />
                        <form action="~/Shows/ShowShow" method="post">
                            <input type="hidden" name="ID" value="@s.Name" /><br />
                            <input type="submit" value="Show show" />
                        </form>
                    </td>

                    <td>@s.Type</td>
                    <td>@s.Start</td>
                    <td>@s.Duration</td>
                    <td>@s.Address.Street, @s.Address.City, @s.Address.ZipCode</td>
                    <td>@s.Price</td>
                    <td>@s.Rating</td>
                    <td><img alt="picture" src="~/Content/@s.Picture" /></td>
                    <td>
                        <form action="~/Buyer/BuyFormView" method="post">
                            <input type="hidden" value="@s.Name" name="ID" />
                            <input type="submit" value="Buy!" />
                        </form>
                    </td>
                </tr>

            }
        </table>

    </div>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
</body>

Projekat/Views/Buyer/BuyTicketForm.cshtml
@{
    ViewBag.Title = "BuyTicketForm";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />

</head>
<body>
    <h2>Tickets for show: @ViewBag.showBuy.Name</h2><br />
    <h3>Date: @ViewBag.buyShow.Time</h3>
    <br />
    <br />
    <form method="post" action="/Buyer/Confirmation">
        <table>
            <tr>
                <td>Amount:</td>
                <td><input type="text" value="1" name="amount" required /></td>
            </tr>
            <tr>
                <td>Tip:</td>
                <td>
                    <select name="type" required>
                        <option value="Regular">Regular</option>
                        <option value="FanPit">FanPit</option>
                        <option value="VIP">VIP</option>
                    </select>
                </td>
            </tr>
            <tr><td><input type="hidden" value="@ViewBag.showBuy.Name" name="ID" /></td></tr>
        </table>
        <br />
        <input type="submit" value="Continue" />
    </form>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>


</body>

Projekat/Views/Buyer/Confirmation.cshtml
@{
    ViewBag.Title = "Confirmation";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
    <script>
        function submitResult() {
            if (confirm("Are you sure you want to confirm the purchase: \nAmount: @ViewBag.ticketnumber \nDiscount:@ViewBag.discount % \nPrice:@ViewBag.price \nTip:@ViewBag.type") == false) {
                return false;
            } else {
                return true;
            }
        }
    </script>
</head>
<body>
    <form action="~/Buyer/Buy" method="post" onsubmit="return submitResult();">
        <br />
        <br />
        <br />
        <table>
            <tr>
                <td>Show:</td>
                <td>@ViewBag.showBuy.Name <input type="hidden" value="@ViewBag.showBuy.Name" name="ID" /></td>
            </tr>
            <tr>
                <td>Amount of tickets:</td>
                <td>@ViewBag.ticketnumber <input type="hidden" value="@ViewBag.ticketnumber" name="ticketNumber" /></td>
            </tr>
            <tr>
                <td>Ticket type:</td>
                <td>@ViewBag.type<input type="hidden" value="@ViewBag.type" name="type" /></td>
            </tr>
            <tr>
                <td>Discount:</td>
                <td>@ViewBag.discount %<input type="hidden" value="@ViewBag.discount" name="type" /></td>
            </tr>
            <tr>
                <td>Total price:</td>
                <td>@ViewBag.price<input type="hidden" value="@ViewBag.price" name="price" /></td>
            </tr>
        </table>
        <input type="submit" value="Buy" />
    </form>
</body>

Projekat/Views/Buyer/LoggedInBuyer.cshtml
@{
    ViewBag.Title = "LoggedInBuyer";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css">
</head>
<body>

    <br />
    <br />
    <div style="float:left;font-size:large;" class="Alink">
        @Html.ActionLink("Buy a Ticket", "BuyTicketView", "Buyer")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="Alink">
        @Html.ActionLink("My Profile", "MyProfile", "Buyer")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="Alink">
        @Html.ActionLink("My tickets", "BoughtTicketsView", "Buyer")
    </div>
    <br />
    <br />
    <div style="float:left;font-size:large;" class="link">
        @Html.ActionLink("Log Out", "Logout", "Buyer")
    </div>
    <br />
    <br />
    <br />
    <br />

    
</body>

Projekat/Views/Buyer/MyProfile.cshtml
@{
    ViewBag.Title = "MyProfile";
}

<head>
    <link rel="stylesheet" href="~/Content/basic.css" type="text/css" />
</head>
<body>
    <br />
    <br />
    <br />
    <br />
    <form action="/Buyer/EditProfile" method="post">
        <table border="1">
            <tr>
                <td id="first">Name:</td>
                <td><input type="text" value="@ViewBag.user.Name" name="name" /></td>
            </tr>
            <tr>
                <td id="first">Surname:</td>
                <td><input type="text" value="@ViewBag.user.Surname" name="surname" /></td>
            </tr>
            <tr>
                <td id="first">Username:</td>
                <td>@ViewBag.user.Username</td>
            </tr>
            <tr>
                <td id="first">password:</td>
                <td><input type="text" value="@ViewBag.user.Password" name="password" /></td>
            </tr>
            <tr>
                <td id="first">Date of birth:</td>
                <td>@ViewBag.user.Birthday</td>
            </tr>
            <tr>
                <td id="first">Role:</td>
                <td>@ViewBag.user.Role</td>
            </tr>
        </table>
        <input type="submit" value="Submit changes" />
    </form>
    <div class="link">
        @Html.ActionLink("<<Home", "Index", "Buyer");
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</body>

Projekat/Views/Buyer/NoTickets.cshtml
@{
    ViewBag.Title = "NoTickets";
}

<h2>NoTickets</h2>
<head>
    <link rel="stylesheet" href="~/Content/error.css" />
</head>
<body>
    <br />
    <br />
    We're sorry, but we don't have that many tickets. Remaining tickets: @ViewBag.seatnumber.
    @Html.ActionLink("<<Back", "BuyFormView", "Buyer")
    <br />
    <br />
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</body>

Projekat/Views/Buyer/Review.cshtml
@{
    ViewBag.Title = "Review";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    Leave your comment and rate the show!
    <form action="/Buyer/Review" method="post">
        Show: @ViewBag.show<br />
        <br />
        <input type="text" placeholder="Comment" name="comment" />
        <br />
        <select name="rating">
            <option value="1">*</option>
            <option value="2">**</option>
            <option value="4">***</option>
            <option value="4">****</option>
            <option value="5">*****</option>
        </select>
        <br />
        <input type="hidden" value="@ViewBag.show" name="IDShow" />
        <input type="submit" value="Submit review!" />
    </form>
    <br />
    <br />
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
</body>

Projekat/Views/Buyer/ShowBoughtTickets.cshtml
@{
    ViewBag.Title = "ShowBoughtTickets";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css" type="text/css" />
</head>
<body>
    <br />
    <br />
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
    <div>
        <form method="post" action="~/Buyer/Search">
            <br />
            Pretraži:
            <input type="text" placeholder="Search ticket" name="search_value" value="" required />
            <br />
            <br />

            &nbsp;
            <select name="priceFrom" required>
                <option value="" selected disabled hidden>Minimum price</option>
                <option value="1000">1000</option>
                <option value="2000">2000</option>
                <option value="3000">3000</option>
                <option value="4000">4000</option>
                <option value="5000">5000</option>
                <option value="10000">10000</option>
                <option value="15000">15000</option>
                <option value="20000">20000</option>
            </select>
            &nbsp;
            <select name="priceTo" required>
                <option value="" selected disabled hidden>Maximum price</option>
                <option value="5000">5000</option>
                <option value="10000">10000</option>
                <option value="15000">15000</option>
                <option value="20000">20000</option>
                <option value="25000">25000</option>
                <option value="30000">30000</option>
                <option value="35000">35000</option>
                <option value="100000">100000</option>
            </select>
            &nbsp; From: &nbsp; <input type="date" name="dateFrom" min="2020-09-23" max="2020-12-31" value="" required />
            &nbsp; To: &nbsp;<input type="date" name="dateTo" min="2020-09-23" max="2020-12-31" value="" required />
            &nbsp;<input type="submit" value="Search" />
        </form>
    </div>
    <br />
    <div>
        Sort search:
        <form method="post" action="~/Buyer/Sort">
            &nbsp; <select name="sortType">
                <option value="ascending">Ascending</option>
                <option value="descending">Descending</option>
            </select>
            &nbsp; <select name="sortBy">
                <option value="Name">Name</option>
                <option value="dateITime">Date and Time</option>
                <option value="price">Price</option>
            </select>
            &nbsp;<input type="submit" value="Sort" />
        </form>
    </div>
    <br />
    <div>
        Filter search:
        <form method="post" action="~/Buyer/Filter">
            &nbsp;  <select name="type">
                <option value="">Choose ticket type</option>
                <option value="Regular">Regular</option>
                <option value="FanPit">FanPit</option>
                <option value="VIP">VIP</option>
            </select>
            &nbsp; <select name="status">
                <option value="">Choose show status</option>
                <option value="active">Active tickets</option>
                <option value="inactive">Inactive tickets</option>
            </select>
            &nbsp; <input type="submit" value="Filter" />
        </form>
    </div>
    <table>
        <tr>
            <th>ID:</th>
            <th>Name</th>
            <th>Date</th>
            <th>Duration</th>
            <th>Total Price</th>
            <th>Amount</th>
            <th>Ticket type</th>
            <th></th>

        </tr>
        @foreach (var t in ViewBag.tickets)
        {
            <tr>
                <td>@t.Id</td>
                <td>@t.Name</td>
                <td>@t.Time</td>
                <td>@t.Duration</td>
                <td>@t.TotalPrice</td>
                <td>@t.Amount</td>
                <td>@t.Type</td>
                <td>
                    <form action="/Buyer/ReviewView" method="post">
                        <input type="submit" value="Add Review" />
                        <input type="hidden" value="@t.Show.Name" name="IDShow" />
                    </form>
                </td>
            </tr>
        }
    </table>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
</body>

Projekat/Views/Buyer/SuccessfulBuy.cshtml
@{
    ViewBag.Title = "SuccessfulBuy";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css">
</head>
<body>
    <h2>You successfully bought tickets!</h2>
    <div class="link">
        @Html.ActionLink(">>Check bought tickets", "BoughtTicketsView", "Buyer");
    </div>
    <div class="link">
        @Html.ActionLink(">>Back to shop", "BuyTicketView", "Buyer");
    </div>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
</body>

Projekat/Views/Buyer/SuccessfulReview.cshtml
@{
    ViewBag.Title = "SuccessfulReview";
}

<head>
    <link rel="stylesheet" href="~/Content/Home.css">
</head>
<body>
    <h2>Successfully reviewed!</h2>
    <div class="link">
        @Html.ActionLink(">>Check bought tickets", "BoughtTicketsView", "Buyer");
    </div>
    <div class="link">
        @Html.ActionLink(">>Home", "Index", "Buyer");
    </div>
</body>